main: de.deltasiege.SmartRedstone.SmartRedstone
name: SmartRedstone
version: '1.0.2'
api-version: 1.13
load: POSTWORLD
description: Rust like Smart Things (+ Companion App)
authors: [undeaD_D, Juli971Master]
commands:
  sd:
    description: Smart Redstone command
    usage: /sd <option>