main: de.deltasiege.SmartRedstone.SmartRedstone
name: SmartRedstone
api-version: 1.16
version: '1.0.1'
load: POSTWORLD
description: Rust like Smart Things (+ Companion App)
authors: [undeaD_D, Juli971Master]